# Generated by Django 5.2.5 on 2026-06-17 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_job_completed_job_completion_requested'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('job', 'freelancer')},
        ),
    ]
